IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lessons' AND COLUMN_NAME = 'Lesson_date' AND TABLE_SCHEMA = 'SummerPractice')
BEGIN
    ALTER TABLE [SummerPractice].[Lessons]
    ADD [Lesson_date] DATETIME DEFAULT GETDATE();
END;